name: Development-CICD-Workflow

on: 
  workflow_dispatch:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node 17
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: install dependencies
        run: npm i
      - name: eslint 
        run:  echo "Linting..."
       
  develop:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - run: npm install
      # - run: npm start  --if-present 

      - name: Run a multi-line script 
        run: |
          echo Add other actions to build
          echo test, and deploy your project

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true 
          ref: Preflight
