name: Testing

on: 
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  test-job:
    name: Test Step 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: env 