name: Preflight

on:
  workflow_dispatch:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test



jobs:
  preflight-job:
    name: Preflight Step 
    runs-on: ubuntu-latest
    steps:
      - run: env 
  
  test:
    runs-on: ubuntu-latest
    needs: [preflight-job]
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
