name: Preflight

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  preflight-job:
    name: Preflight Step 
    runs-on: ubuntu-latest
    steps:
      - run: env 
  
  test:
    runs-on: ubuntu-latest
    needs: [preflight-job]
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
      
      - name: Run Custom Action
        uses: ./.github/actions/custom
        id: display
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}
          attempt_number: ${{ github.run_attempt }}

      - name: Spit out outputs
        id: display-result
        run: |
          echo "html_url: ${{ steps.display.outputs.html_url }}"
          echo "Conclusion: ${{ steps.display.outputs.conclusion }}"
          echo "created_at: ${{ steps.display.outputs.created_at }}"
          echo "started_at: ${{ steps.display.outputs.started_at }}"

      - name: Generate list using Markdown
        run: |
          echo "Run generated at ${{ steps.display.outputs.created_at }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      
      - name: Generate Info Annotations
        if: steps.display-result.outcome != 'success'
        run: |
          echo "::warning ::Review needed"


  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Annotate PR must work
        uses: ./.github/actions/pr-metadata
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  list-jobs:
    runs-on: ubuntu-latest
    needs: [annotate-pr]
    steps:
      - uses: actions/checkout@v2

      - name: List Job Summaries for a Workflow Run
        uses: ./.github/actions/job-summaries
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}

